[package]
name        = "flix-assertions"
description = "Additional assertions with a custom error message and infix symbols."
version     = "0.3.0"
flix        = "0.35.0"
license     = "Apache-2.0"
authors     = ["Roland Csaszar"]
