# SPDX-FileCopyrightText:  Copyright 2023 Roland Csaszar
# SPDX-License-Identifier: Apache-2.0
#
# Project:  flix-assertions
# File:     test.yml
# Date:     03.May.2023
#
# ==============================================================================

name: Test

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  tests:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]

    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install flix
        run: |
          curl -L https://github.com/flix/flix/releases/download/v0.35.0/flix.jar --output ./flix.jar

      - name: Run Tests - Not Windows
        if: runner.os != 'Windows'
        run: |
          $JAVA_HOME_17_X64/bin/java -jar flix.jar test

      - name: Run Tests - Windows
        if: runner.os == 'Windows'
        run: |
          & "${env:JAVA_HOME_17_X64}\bin\java" -jar flix.jar test
